### ISSUE TITLE
Not works well in macro

### ISSUE THREAD

**Issue by gukz** [gukz/ftFT.nvim#7]
if your macro contains ftFT operations, this plugin could cause your macro to behave strangely.

**Comment by MenBrial** [comment]
It seems this issue comes from the usage of the 'nvim_feedkeys' function: the mode should be 'ni' to insert the keys immediately in the typeahead buffer. Otherwise, the keys are added after any remaining characters from the current macro/mapping.

See the help for 'feedkeys'.

The lightspeed plugin has a similar issue: https://github.com/ggandor/lightspeed.nvim/issues/7.

**Comment by gukz** [comment]
Thanks @MenBrial  a lot~

**Comment by MenBrial** [comment]
You're welcome!
